name: prod-bot

networks:
  bot-net:

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:


services:
  bot:
    image: cr.yandex/${CONTAINER_REGISTRY}/bot-prod:latest
    container_name: bot-prod
    command: python -m bot.src.main
    networks:
      - bot-net
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    container_name: postgres-bot-dev
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
      start_interval: 1s


  prometheus:
    image: prom/prometheus
    container_name: prometheus-local
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - bot-net
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - bot

  grafana:
    image: grafana/grafana
    container_name: grafana-local
    env_file:
      - .env
    ports:
      - "3030:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - bot-net
    depends_on:
      - prometheus
    restart: unless-stopped
