# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 5, "", "service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rservice.proto\x12\x07service\x1a\x1bgoogle/protobuf/empty.proto"\xa1\x01\n\x12\x46\x65\x65\x64\x62\x61\x63kSchemaGRPC\x12\'\n\x04type\x18\x01 \x01(\x0e\x32\x19.service.FeedbackTypeGRPC\x12@\n\x15\x63ommunication_channel\x18\x02 \x01(\x0e\x32!.service.CommunicationChannelGRPC\x12\x0f\n\x07\x63ontact\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t"F\n\x14\x46\x65\x65\x64\x62\x61\x63kResponseGRPC\x12.\n\tfeedbacks\x18\x01 \x03(\x0b\x32\x1b.service.FeedbackSchemaGRPC*Q\n\x10\x46\x65\x65\x64\x62\x61\x63kTypeGRPC\x12\x08\n\x04HELP\x10\x00\x12\x0e\n\nSUGGESTION\x10\x01\x12\x07\n\x03\x42UG\x10\x02\x12\x0f\n\x0bPARTNERSHIP\x10\x03\x12\t\n\x05OTHER\x10\x04*3\n\x18\x43ommunicationChannelGRPC\x12\t\n\x05\x45MAIL\x10\x00\x12\x0c\n\x08TELEGRAM\x10\x01\x32W\n\x0c\x46\x65\x65\x64\x62\x61\x63kGRPC\x12G\n\x0eGetAllFeedback\x12\x16.google.protobuf.Empty\x1a\x1d.service.FeedbackResponseGRPCb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_FEEDBACKTYPEGRPC"]._serialized_start = 291
    _globals["_FEEDBACKTYPEGRPC"]._serialized_end = 372
    _globals["_COMMUNICATIONCHANNELGRPC"]._serialized_start = 374
    _globals["_COMMUNICATIONCHANNELGRPC"]._serialized_end = 425
    _globals["_FEEDBACKSCHEMAGRPC"]._serialized_start = 56
    _globals["_FEEDBACKSCHEMAGRPC"]._serialized_end = 217
    _globals["_FEEDBACKRESPONSEGRPC"]._serialized_start = 219
    _globals["_FEEDBACKRESPONSEGRPC"]._serialized_end = 289
    _globals["_FEEDBACKGRPC"]._serialized_start = 427
    _globals["_FEEDBACKGRPC"]._serialized_end = 514
# @@protoc_insertion_point(module_scope)
